- Added in Pixel 2XL configuration.
maruos/manifest pull request #22
Opened 2021-11-03 23:32 UTC by bootlessxfly

Points to my personal repo for now.

Signed-off-by: Chris White <bootlessxfly@gmail.com>

This is only for the Pixel 2 XL. I can go update my pixel 2 trees and kernel defconfig if you guys want that. I've built for the pixel 2, but have not device to test it. 

Also, this includes my personal device and kernel repos. I am not sure the correct process on adding this into the maruos repo. Let me know if there is antrthing needed on my end.

2021-11-04 02:19 UTC, utzcoz commented
@bootlessxfly Thanks for your work for Pixel 2. It's not recommended to use personal GitHub repo for MaruOS. If you ensure you have finished the porting of Pixel 2, you can contact @pdsouza to grant your permission to create Pixel 2 repositories under MaruOS org account and push your source code Pixel related repositories.

2021-11-04 22:00 UTC, bootlessxfly commented
> @bootlessxfly Thanks for your work for Pixel 2. It's not recommended to use personal GitHub repo for MaruOS. If you ensure you have finished the porting of Pixel 2, you can contact @pdsouza to grant your permission to create Pixel 2 repositories under MaruOS org account and push your source code Pixel related repositories.

@utzcoz Ill reach out to @pdsouza about getting this set up. Ill update this PR when that gets sorted out

2021-11-05 01:49 UTC, pdsouza commented
Just invited you to the maruos org @bootlessxfly! Once you are a member you can create or fork the Pixel 2 repos directly on our org, much like @utzcoz has done so for Pixel 3a. 

Very exciting to see support landing for the Pixel 2XL and Pixel 2 soon!

2022-08-16 18:32 UTC, pintaf commented
Hello @bootlessxfly if you created the device repo under maruos org, maybe you can update your to reflect these changes ?

2023-08-01 01:50 UTC, utzcoz requested changes

2023-08-01 01:50 UTC, utzcoz commented on default.xml
> +    <!-- START Wahoo/Taimen - Google Pixel 2XL -->
Align your indents

2023-08-01 01:50 UTC, utzcoz commented on default.xml
> +
If you don't add new line or delete old line, it's not recommended to modify lines like this one.

2023-08-01 01:50 UTC, utzcoz commented on default.xml
> +           fetch="https://github.com/bootlessxfly"
Please push your device repositories to maruos org like Pixel3a.

2023-08-12 09:45 UTC, utzcoz commented
@bootlessxfly If you need, I can help you to setup repositories in maruos org. Feel free to ping me if you need any help.

2023-08-15 23:09 UTC, bootlessxfly commented on default.xml
> +           fetch="https://github.com/bootlessxfly"
Hi! I did not see that this PR wazs dangling for all this time. Sorry about that!

The device tress where pushed to maruos almost 2 years ago now, but I guess for some unknown reason I never changed that here. I just pushed a update that points to the maruos tree. I think this is all that is needed?

2023-08-16 03:20 UTC, utzcoz commented on default.xml
> +
@bootlessxfly nit: What about removing this empty line? It's great to merge after this change.

2023-08-16 20:58 UTC, bootlessxfly commented on default.xml
> +
done!

2023-08-17 00:47 UTC, merged

2023-08-17 00:49 UTC, pdsouza commented
Thanks @bootlessxfly for the quick fixes! Looking forward to more of your contributions!

2023-08-17 00:49 UTC, utzcoz commented
@bootlessxfly merged. Please test the latest 0.7 branch to check whether it works as you expected. It's great news we have Pixel 2L source code supporting now.